### ISSUE TITLE
Expired Token Issue (Not Auto Refreshing)

### ISSUE THREAD

**Issue by rishabhbizzle** [spotify/spotify-web-api-ts-sdk#64]
Hey, I have been using this SDK for a week, and now this error has come up. I know the token is expired but you mentioned that the SDK does auto-refresh the token so why is it not doing that?

<img width="780" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/100997409/830c9f54-3fa8-456c-929d-821453d2d6eb">

**Comment by rishabhbizzle** [comment]
can someone help me with this issue ??

**Comment by davidwhitney** [comment]
Interesting, it looks like the `ClientCredentialsStrategy` isn't providing a refresh mechanism - this is because the Bearer token returned from a client credentials auth flow doesn't include a refresh token.

I'm imagining that your token is expiring after 60 minutes of activity. Is that what you're seeing?

Luckily, while it's not strictly a "token refresh", because client creds flow has both the client Id and secret it's easy to just request another token on expiry so should be a small change to that strategy.

**Comment by rishabhbizzle** [comment]
> 

It's been 2 days and I'm still getting this error :(

**Comment by rishabhbizzle** [comment]
> Interesting, it looks like the `ClientCredentialsStrategy` isn't providing a refresh mechanism - this is because the Bearer token returned from a client credentials auth flow doesn't include a refresh token.
> 
> I'm imagining that your token is expiring after 60 minutes of activity. Is that what you're seeing?
> 
> Luckily, while it's not strictly a "token refresh", because client creds flow has both the client Id and secret it's easy to just request another token on expiry so should be a small change to that strategy - I've got a WIP PR ready to go.

It's been 2 days and I'm still getting this error :(

**Comment by davidwhitney** [comment]
Have you restarted the process that has the cached token during those two days?

**Comment by davidwhitney** [comment]
^ this should now be fixed on the next package release.

**Comment by steezplusplus** [comment]
![Screen Shot 2023-09-05 at 6 14 41 PM](https://github.com/spotify/spotify-web-api-ts-sdk/assets/9201173/85ac27a7-a6f9-46d3-8b81-1b8c932a5560)

Same code as the OP uses

**Comment by davidwhitney** [comment]
@rishabhbizzle and is this running inside a browser context? I'm guessing from your stack trace.

I think that's perhaps consistent - it's loading the outdated token from the cache, doesn't have a refresh mechanism, so it's trying to use it and erroring. If you clear your local storage, does it work again?

I've just started running a test now that'll run for a few hours to try verify...

**Comment by rishabhbizzle** [comment]
> @rishabhbizzle and is this running inside a browser context? I'm guessing from your stack trace.
> 
> I think that's perhaps consistent - it's loading the outdated token from the cache, doesn't have a refresh mechanism, so it's trying to use it and erroring. If you clear your local storage, does it work again?
> 
> I've just started running a test now that'll run for a few hours to try verify...

I tried after clearing local storage it still doesn't work. I am using this in my Next.js project this is how the code structure looks like
<img width="432" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/100997409/84ed3763-628c-4b0d-8e9c-d235fe23d8e4">
<img width="492" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/100997409/c6be1870-d479-4f42-89ff-f7a85f20ac52">

**Comment by davidwhitney** [comment]
No, your implementation looks totally fine at a glance. It's weird that it'd work for a couple of days - I wonder if your API key has changed / been revoked / been modified in some way? (I don't work for Spotify; I can't help you there!)

All I could think of is bad cached data, but if you've cleared local storage, and still have the keys and it doesn't work fresh, I'm at a bit of a loss - it just suggests the API keys themselves are bad...

**Comment by davidwhitney** [comment]
Quick update, the test run I did with some additional refresh code ran for 10 hours happily - have you verified your token info is still correct?

**Comment by oogunjob** [comment]
I'm also experiencing the same issue

**Comment by rishabhbizzle** [comment]
> Quick update, the test run I did with some additional refresh code ran for 10 hours happily - have you verified your token info is still correct?

Yes I verified even after manually refreshing token using ```authenticate()``` function the new token gets issues but it still doesn't work and continues to give the same "Bad or Expired Token"

**Comment by wintercounter** [comment]
Has anyone found a solution to this? Now I have to restart my server with CRON once a day to overcome this which is less than ideal. Not to mention I'm losing my in-memory cache with that.

**Comment by wintercounter** [comment]
You guys are trying to use it with Next.js 13, right? I believe I know what's the problem. Next caches all fetch requests by default. `cache: 'force-cache'` is the default value for all fetch requests. We cannot control fetch options for Auth Strategies, so there is no way to solve this in userland.

I tried adding `cache: 'no-store'` inside the package's dist folder, cleared webpack and swc cache and it seems like it solves this issue: https://github.com/spotify/spotify-web-api-ts-sdk/blob/main/src/auth/ClientCredentialsStrategy.ts#L67C31-L67C31

It's a pretty dumb default if you ask me (like many other things in Next). Not sure adding `cache: no-store` to the API client is the right solution as it's a non-standard value. Probably using the user-provided `fetch` for auth requests also would be a better way.

**Comment by wintercounter** [comment]
I just want to give an update on this. I added a script to my codebase to monkey-patch the source files, and since then I don't have token issues anymore, the app has been running on prod for 4 days now. Next should not cache POST requests or when the Authorization header is present. It doesn't create a cache file, but still, something is wrong under the hood there. I'm thinking of creating an issue for them, but the repro is not an easy case.

Here's the script if anyone else wants to experiment with it:

```js
import fs from 'node:fs/promises'

const spotifyApiDistPath = './node_modules/@spotify/web-api-ts-sdk/dist'
const spotifyApiMjsPath = `${spotifyApiDistPath}/mjs/auth/ClientCredentialsStrategy.js`
const spotifyApiCjsPath = `${spotifyApiDistPath}/cjs/auth/ClientCredentialsStrategy.js`
const paths = [spotifyApiMjsPath, spotifyApiCjsPath]

const patch = async path => {
    const content = await fs.readFile(path, 'utf-8')
    await fs.writeFile(path, content.replace(/body: bodyAsString\s/g, `body: bodyAsString, cache: 'no-store'`))
}

paths.forEach(patch)

console.log('Patched Spotify API')
```

**Comment by jackblanc** [comment]
Can confirm the above issue worked for me. I added this script as a "postinstall" command in my package.json.

**Comment by rishabhbizzle** [comment]
> I just want to give an update on this. I added a script to my codebase to monkey-patch the source files, and since then I don't have token issues anymore, the app has been running on prod for 4 days now. Next should not cache POST requests or when the Authorization header is present. It doesn't create a cache file, but still, something is wrong under the hood there. I'm thinking of creating an issue for them, but the repro is not an easy case.
> 
> Here's the script if anyone else wants to experiment with it:
> 
> ```js
> import fs from 'node:fs/promises'
> 
> const spotifyApiDistPath = './node_modules/@spotify/web-api-ts-sdk/dist'
> const spotifyApiMjsPath = `${spotifyApiDistPath}/mjs/auth/ClientCredentialsStrategy.js`
> const spotifyApiCjsPath = `${spotifyApiDistPath}/cjs/auth/ClientCredentialsStrategy.js`
> const paths = [spotifyApiMjsPath, spotifyApiCjsPath]
> 
> const patch = async path => {
>     const content = await fs.readFile(path, 'utf-8')
>     await fs.writeFile(path, content.replace(/body: bodyAsString\s/g, `body: bodyAsString, cache: 'no-store'`))
> }
> 
> paths.forEach(patch)
> 
> console.log('Patched Spotify API')
> ```

How did you manage to make this work in production? assuming you used vercel for the deployment @wintercounter 

<img width="179" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/100997409/df0ca59e-bef8-4fc1-bcf7-6e3de394d02f">

Like I've added the patch script before next build in build command but it still giving this error on prod
<img width="477" alt="image" src="https://github.com/spotify/spotify-web-api-ts-sdk/assets/100997409/7bd16650-c409-46ad-9d57-69dacdbf01cb">

**Comment by wintercounter** [comment]
I'm running it after install.

![image](https://github.com/spotify/spotify-web-api-ts-sdk/assets/963776/a0b4648e-e635-47fb-885d-6cd36b85a450)

https://github.com/wintercounter/dnbop

**Comment by rishabhbizzle** [comment]
> I'm running it after install.
> 
> ![image](https://private-user-images.githubusercontent.com/963776/310247969-a0b4648e-e635-47fb-885d-6cd36b85a450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NjU2ODEsIm5iZiI6MTcwOTY2NTM4MSwicGF0aCI6Ii85NjM3NzYvMzEwMjQ3OTY5LWEwYjQ2NDhlLWU2MzUtNDdmYi04ODVkLTZjZDM2Yjg1YTQ1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxOTAzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MmQ5MjRkZmUwMzA2ZjU5ZjkwNDI2ZDk1MzMzODM1M2EzYzIxY2Y3MmM3MjFiNzc4YzU4ZTI5ZDk1MTU1YjliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hcgqytRifLeqY8VwtB_OUn24c1AE-rQmfwtO69TqydM)
> 
> https://github.com/wintercounter/dnbop

tried this and it's still not working :(

**Comment by wintercounter** [comment]
Seems like to me you get this immediately, so it doesn't even wait for the token to get expired. So maybe it's a different issue?

It's also possible that this doesn't work with the latest version of the client. Maybe the code was changed recently and it fails to replace. Just a guess. Maybe you can try with the version I'm using.

Does the script replacing it for you locally?

**Comment by rishabhbizzle** [comment]
Yes I ran the script locally 12 days ago (with the latest version of the client) and it fixed the issue and working smoothly from then on local

**Comment by strenkml** [comment]
I am having this error as well. Except instead of working for a short period of time, mine never works.

I am authenticating with this: `SpotifyApi.withClientCredentials(this.clientId, this.clientSecret);`

I created the app in the dev panel and copied the clientId and clientSecret to my code. I have confirmed that the method is getting passed the correct values.

**Comment by rotemdoron** [comment]
happening to me as well, tried using the patch in nextjs but didn't work, im calling the sdk from an api route and get the same error, if i call it from a server action it works, not sure why, i tried with "use server" and without but no luck, anything on that?

**Comment by braswelljr** [comment]
getting the same token issues

**Comment by csfrey** [comment]
I'm also having this issue but oddly the issue doesn't happen with search, only when I try to fetch tracks by id. Also found that rotating the client secret seems to temporarily stop the issue.
